[tool.poetry]
name = "turbopuffer"
version = "0.1.0"
description = "Python Client for accessing the Turbopuffer API"
documentation = "https://turbopuffer.com/docs"
authors = ["Jacob Wirth <xthexder@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31"

[tool.poetry.dev-dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
