[tool.poetry]
name = "turbopuffer"
version = "0.1.0"
description = "Python Client for accessing the turbopuffer API"
documentation = "https://turbopuffer.com/docs"
authors = ["Jacob Wirth <info@turbopuffer.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31"
annotated-types = "^0.6.0"
dataclass-wizard = "^0.22.2"

[tool.poetry.dev-dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
